# -*- coding: utf-8 -*-
"""loteria.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AsAehACpxdzTXzVPaerg_pa8V69nIWMs
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pandas_profiling import ProfileReport

from google.colab import drive
drive.mount('/content/drive')

path = "/content/drive/MyDrive/Colab Notebooks/loteria/lottery_data.csv"
dflottery = pd.read_csv(path)

!pip install https://github.com/pandas-profiling/pandas-profiling/archive/master.zip

profile = ProfileReport(dflottery, title="Pandas Profiling Report")

profile

profile.to_file(output_file="profile.html")

dflottery.tail()

dflottery.columns

df_powerball=dflottery["powerball"].sort_values(ascending=True).unique()
df_powerplay=dflottery["powerplay"].sort_values(ascending=True).unique()
df_powerball_hist=dflottery.groupby("powerball")["powerball"].count()
df_powerplay_hist=dflottery.groupby("powerplay")["powerplay"].count()

plt.bar(df_powerball,df_powerball_hist.tolist())

plt.bar(df_powerplay,df_powerplay_hist.tolist())

day_vs_powerball_total=dflottery.copy()
day_vs_powerball_total['counter']=1

day_powerball_total=dflottery.pivot_table(index='weekday', columns='powerball', values='jackpot', aggfunc='sum')
day_powerball_total

day_vs_powerball=day_vs_powerball_total.pivot_table(index='weekday', columns='powerball', values='counter', aggfunc='sum')
day_vs_powerball

day_vs_powerball_total[(day_vs_powerball_total['weekday']=='Sat') & (day_vs_powerball_total['powerball']==1 )]

